title = "Augustin Godiscal"
baseURL = "/"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
relativeurls = true
pygmentsUseClasses = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  body_classes = "sans-serif"
  description = "Augustin Godiscal"
  legal = "Augustin Godiscal (MIT)"
  mastodon = "https://mamot.fr/@auggod"
  github = "https://github.com/auggod"
  gitlab = ""
  background_color_class = "bg-black"
  featured_image = "/images/1060.jpg"
  recent_posts_number = 10
